using UnityEngine;
using Photon.Pun;

/// <summary>
/// ƒJƒƒ‰‚ÉŠÖ‚·‚éˆ—‚ğ‚Ü‚Æ‚ß‚ÄŠÇ—‚·‚éƒNƒ‰ƒX
/// </summary>
public class CameraController : MonoBehaviourPunCallbacks
{
    [Header(" Elements ")]
    [SerializeField] Transform viewPoint;
    Camera myCamera;

    void Start()
    {
        if (!photonView.IsMine)
            return;

        myCamera = Camera.main;
    }

    void Update()
    { 
        if (!photonView.IsMine)
            return;

        // ˆÊ’uXV
        myCamera.transform.position = viewPoint.position;
        myCamera.transform.rotation = viewPoint.rotation;
    }

    //|||||||||||||||||||||||||||/
    //@Ray¶¬
    //|||||||||||||||||||||||||||/

    // TODO:
    // ‚±‚Ìˆ—‚ğ•ÊƒNƒ‰ƒX‚É•ªŠ„‚·‚éI

    /// <summary>
    /// ƒJƒƒ‰‚©‚çêŠ‚ğw’è‚µ‚ÄRay‚ğ¶¬
    /// </summary>
    /// <param name="generationPos">¶¬‚·‚éÀ•W</param>
    /// <returns>¶¬‚µ‚½Ray</returns>
    public Ray GenerateRay(Vector2 generationPos)
    {
         return myCamera.ViewportPointToRay(generationPos);
    }
}