using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Photon.Pun;
using System;
using UnityEngine.InputSystem;

namespace Guns
{
    /// <summary>
    /// e‚Ìí—Ş‚ğ•\‚·—ñ‹“‘Ì
    /// </summary>
    enum GunType
    {
        HandGun,        // ƒnƒ“ƒhƒKƒ“
        AssaultRifle,   // ƒAƒTƒ‹ƒgƒ‰ƒCƒtƒ‹
        SniperRifle     // ƒXƒiƒCƒp[ƒ‰ƒtƒ‹
    }

    /// <summary>
    /// ƒvƒŒƒCƒ„[‚ÌeŠÇ—ƒNƒ‰ƒX
    /// </summary>
    public class PlayerGunController : MonoBehaviourPunCallbacks
    {
        //|||||||||||||||||||||||||||/
        //@‰ü‘P•”•ª
        //|||||||||||||||||||||||||||/


        [SerializeField] Animator gunAnimator;                  // ƒAƒNƒVƒ‡ƒ“‚É“‡‚·‚éŠ´‚¶‚ÅƒŠƒtƒ@ƒNƒ^ƒŠƒ“ƒO‚·‚éI
        [SerializeField] CameraController cameraController;     // ƒAƒNƒVƒ‡ƒ“‚É“‡‚·‚éŠ´‚¶‚ÅƒŠƒtƒ@ƒNƒ^ƒŠƒ“ƒO‚·‚é!
        [SerializeField] PlayerAnimator playerAnimator;         // ƒAƒNƒVƒ‡ƒ“‚É“‡‚·‚éŠ´‚¶‚ÅƒŠƒtƒ@ƒNƒ^ƒŠƒ“ƒO‚·‚éI

        //|||||||||||||||||||||||||||/

        [Header(" ƒf[ƒ^ŠÖ˜A ")]
        [SerializeField] GunData[] gunDates;                // eƒf[ƒ^ˆê——
        List<GameObject> guns = new List<GameObject>();     // eDataŠÇ——p
        List<int> ammunition = new List<int>();             // Œ»İ‚ÌŠ’e–ò
        List<int> ammoClip = new List<int>();               // ƒ}ƒKƒWƒ““à‚Ì’e–ò
        GunType selectedGunType = GunType.HandGun;          // Œ»İ‘I‘ğ’†‚Ìeí—Ş
        float shotTimer;                                    // ËŒ‚ŠÔŠu

        [Header(" Œ©‚½–ÚŠÖ˜A ")]
        [SerializeField] GameObject[] gunsHolder;       // ©•ª‹“_‚Ìe
        [SerializeField] GameObject[] otherGunsHolder;  // ‘Šè‹“_‚Ìe


        void Start()
        {
            // g—p‚·‚éeƒzƒ‹ƒ_[‘I‘ği©•ª‹“_‚©‘Šè‹“_‚©‚ğŠî‚ÉŒˆ’èj
            GameObject[] selectedGunsHolder = photonView.IsMine ? gunsHolder : otherGunsHolder;

            // e“o˜^
            foreach (GameObject gun in selectedGunsHolder)
                guns.Add(gun);

            // ©g‚Ìê‡‚Ì‚İA’e–ò‚Æƒ}ƒKƒWƒ“‚Ì‰Šú‰»
            if (photonView.IsMine)
            {
                foreach (var gun in gunDates)
                {
                    ammunition.Add(gun.MaxAmmunition);  // Š’e–ò
                    ammoClip.Add(gun.MaxAmmoClip);      // ƒ}ƒKƒWƒ““à’e–ò
                }

                // ƒY[ƒ€ŠÖ˜Aˆ—“o˜^
                InputManager.Controls.Gun.Zoom.started += ZoomIn;
                InputManager.Controls.Gun.Zoom.canceled += ZoomOut;
            }

            // e‚Ì•\¦Ø‘Ö
            ChangeActiveGun();
        }
        void OnDestroy()
        {
            // ©g‚ª‘€ì‚·‚éƒIƒuƒWƒFƒNƒg‚Å‚È‚¯‚ê‚Îˆ—‚ğƒXƒLƒbƒv
            if (!photonView.IsMine)
                return;

            // ƒY[ƒ€ŠÖ˜Aˆ—‰ğœ
            InputManager.Controls.Gun.Zoom.started -= ZoomIn;
            InputManager.Controls.Gun.Zoom.canceled -= ZoomOut;
        }

        void Update()
        {
            // ©•ªˆÈŠO‚È‚çˆ—I—¹
            if (!photonView.IsMine)
                return;

            // e‚ÌØ‚è‘Ö‚¦
            SwitchingGuns();

            // ËŒ‚ŠÖ”
            Fire();

            // ƒŠƒ[ƒhŠÖ”
            if (Input.GetKeyDown(KeyCode.R))
                Reload();

            // ’e–òƒeƒLƒXƒgXV
            UIManager.instance.SettingBulletsText(gunDates[(int)selectedGunType].MaxAmmoClip,
                ammoClip[(int)selectedGunType], ammunition[(int)selectedGunType]);
        }

        //|||||||||||||||||||||||||||/
        //@•ŠíØ‚è‘Ö‚¦
        //|||||||||||||||||||||||||||/

        /// <summary>
        /// e‚ÌØ‚è‘Ö‚¦ƒL[“ü—Í‚ğŒŸ’m
        /// </summary>
        public void SwitchingGuns()
        {
            int gunCount = Enum.GetValues(typeof(GunType)).Length;

            // ƒ}ƒEƒXƒzƒC[ƒ‹‚Å‚Ìe‚ÌØ‚è‘Ö‚¦
            float mouseScroll = Input.GetAxisRaw("Mouse ScrollWheel");
            if (mouseScroll != 0f)
                UpdateSelectedGunType((int)Mathf.Sign(mouseScroll), gunCount);

            // ”’lƒL[‚Å‚Ìe‚ÌØ‚è‘Ö‚¦
            for (int i = 0; i < guns.Count; i++)
            {
                if (Input.GetKeyDown((i + 1).ToString()))
                {
                    SetGunTypeAndNotify((GunType)i);
                    break; // ƒL[‚ª‰Ÿ‚³‚ê‚½‚çƒ‹[ƒv‚ğ”²‚¯‚é
                }
            }
        }

        /// <summary>
        /// e‚Ìƒ^ƒCƒv‚ğXV‚µA•ÏX‚ğ’Ê’m
        /// </summary>
        void UpdateSelectedGunType(int direction, int gunCount)
        {
            // e‚Ìƒ^ƒCƒv‚ğXV
            selectedGunType += direction;

            // ”ÍˆÍŠO‚É‚È‚ç‚È‚¢‚æ‚¤‚É’²®
            if (selectedGunType < 0)
            {
                selectedGunType = (GunType)(gunCount - 1);
            }
            else if ((int)selectedGunType >= gunCount)
            {
                selectedGunType = GunType.HandGun;
            }

            // XVŒã‚Ìe‚Ìƒ^ƒCƒv‚ğİ’è‚µA’Ê’m
            SetGunTypeAndNotify(selectedGunType);
        }

        /// <summary>
        /// e‚Ìƒ^ƒCƒv‚ğİ’è‚µA•ÏX‚ğ’Ê’m‚·‚é
        /// </summary>
        void SetGunTypeAndNotify(GunType gunType)
        {
            selectedGunType = gunType;
            gunAnimator.SetTrigger("WeaponChange");
            photonView.RPC("SetGun", RpcTarget.All, (int)selectedGunType);
        }

        /// <summary>
        /// e‚ÌØ‚è‘Ö‚¦ˆ—
        /// </summary>
        [PunRPC]
        public void SetGun(int gunNo)
        {
            //e‚ÌØ‚è‘Ö‚¦
            if (gunNo < Enum.GetValues(typeof(GunType)).Length)
            {
                //e‚Ì”Ô†‚ğƒZƒbƒg
                selectedGunType = (GunType)gunNo;

                // ƒAƒjƒ[ƒVƒ‡ƒ“
                playerAnimator.IsWeaponChange();

                // w’èŠÔŒãØ‚è‘Ö‚¦
                StartCoroutine(DelayedSwitchGun(1f));
            }
        }

        /// <summary>
        /// Photon‚ÅŒÄ‚Ño‚·•Ší•ÏXˆ—
        /// </summary>
        /// <param name="waitTime">‘Ò‚¿ŠÔ</param>
        IEnumerator DelayedSwitchGun(float waitTime)
        {
            yield return new WaitForSeconds(waitTime);
            ChangeActiveGun();
        }

        /// <summary>
        /// e‚Ì•\¦Ø‚è‘Ö‚¦
        /// </summary>
        void ChangeActiveGun()
        {
            // ‘S‚Ä‚Ìe‚ğ”ñ•\¦‚É
            foreach (GameObject gun in guns)
                gun.gameObject.SetActive(false);

            // ‘I‘ğ’†‚Ìe‚Ì‚İ•\¦‚·‚é
            guns[(int)selectedGunType].SetActive(true);
        }

        //|||||||||||||||||||||||||||/
        //@ƒY[ƒ€ˆ—
        //|||||||||||||||||||||||||||/

        /// <summary>
        /// e‚ÌƒY[ƒ€ó‘Ô•ÏX‚ÌƒCƒxƒ“ƒgƒnƒ“ƒhƒ‰
        /// </summary>
        public static Action<bool> OnGunZoomStateChanged;

        /// <summary>
        /// ƒY[ƒ€ŠJn
        /// </summary>
        void ZoomIn(InputAction.CallbackContext context)
        {
            OnGunZoomStateChanged?.Invoke(true);
            CameraZoom.OnZoomStateChanged?.Invoke(gunDates[(int)selectedGunType].AdsZoom, gunDates[(int)selectedGunType].AdsSpeed);
        }

        /// <summary>
        /// ƒY[ƒ€I—¹
        /// </summary>
        void ZoomOut(InputAction.CallbackContext context)
        {
            OnGunZoomStateChanged?.Invoke(false);
            CameraZoom.OnZoomStateChanged?.Invoke(60f, gunDates[(int)selectedGunType].AdsSpeed);
        }


        //|||||||||||||||||||||||||||/
        //@”­Ëˆ—‚ÆƒŠƒ[ƒh
        //|||||||||||||||||||||||||||/

        /// <summary>
        /// ¶ƒNƒŠƒbƒN‚ÌŒŸ’m
        /// </summary>
        public void Fire()
        {
            if (Input.GetMouseButton(0) && Time.time > shotTimer)
            {
                // ’e–ò‚Ìc‚è‚ª‚ ‚é‚©”»’è
                if (ammoClip[(int)selectedGunType] == 0)
                {
                    // ’eØ‚ê‚Ì‰¹‚ğ–Â‚ç‚·
                    // ƒAƒjƒ[ƒVƒ‡ƒ“‚ğg—p‚·‚é•û–@‚É•ª‚¯‚é
                    //photonView.RPC("NotShotSound", RpcTarget.All);

                    // ƒI[ƒgƒŠƒ[ƒh
                    Reload();

                    // ˆ—I—¹
                    return;
                }

                //e‚Ì”­Ëˆ—
                FiringBullet();
            }
        }

        /// <summary>
        /// ’eŠÛ‚Ì”­Ë
        /// </summary>
        void FiringBullet()
        {
            // ƒAƒjƒ[ƒVƒ‡ƒ“
            gunAnimator.SetTrigger("Attack");

            // ƒAƒjƒ[ƒVƒ‡ƒ“
            playerAnimator.Attack(AttackType.Short);

            //Ray(Œõü)‚ğƒJƒƒ‰‚Ì’†‰›‚©‚çİ’è
            Vector2 pos = new Vector2(.5f, .5f);
            Ray ray = cameraController.GenerateRay(pos);

            //ƒŒƒC‚ğ”­Ë
            if (Physics.Raycast(ray, out RaycastHit hit))
            {
                //ƒvƒŒƒCƒ„[‚É‚Ô‚Â‚©‚Á‚½ê‡
                if (hit.collider.gameObject.tag == "Player")
                {
                    //ŒŒ‚ÌƒGƒtƒFƒNƒg‚ğƒlƒbƒgƒ[ƒNã‚É¶¬
                    PhotonNetwork.Instantiate(gunDates[(int)selectedGunType].PlayerHitEffect.name, hit.point, Quaternion.identity);

                    // ƒqƒbƒgŠÖ”‚ğ‘SƒvƒŒƒCƒ„[‚ÅŒÄ‚Ño‚µ‚ÄŒ‚‚½‚ê‚½ƒvƒŒƒCƒ„[‚ÌHP‚ğ“¯Šú
                    hit.collider.gameObject.GetPhotonView().RPC("Hit",
                        RpcTarget.All,
                        gunDates[(int)selectedGunType].ShotDamage,
                        photonView.Owner.NickName,
                        PhotonNetwork.LocalPlayer.ActorNumber);
                }
                else
                {
                    //’e­ƒGƒtƒFƒNƒg¶¬ 
                    GameObject bulletImpactObject = Instantiate(gunDates[(int)selectedGunType].NonPlayerHitEffect,
                        hit.point + (hit.normal * .002f),                   //ƒIƒuƒWƒFƒNƒg‚©‚ç­‚µ•‚‚©‚µ‚Ä‚¿‚ç‚Â‚«–h~
                        Quaternion.LookRotation(hit.normal, Vector3.up));   //’¼Šp‚Ì•ûŒü‚ğ•Ô‚µ‚Ä‚»‚Ì•ûŒü‚É‰ñ“]‚³‚¹‚é

                    //ŠÔŒo‰ß‚Åíœ
                    Destroy(bulletImpactObject, 10f);
                }
            }

            //ËŒ‚ŠÔŠu‚ğİ’è
            shotTimer = Time.time + gunDates[(int)selectedGunType].ShootInterval;

            //‘I‘ğ’†‚Ìe‚Ì’e–òŒ¸‚ç‚·
            ammoClip[(int)selectedGunType]--;
        }


        /// <summary>
        /// ƒŠƒ[ƒh
        /// </summary>
        void Reload()
        {
            int gunTypeIndex = (int)selectedGunType;

            // ƒŠƒ[ƒh•â[•ª‚Ì’e”ŒvZ
            int ammoToReload = Math.Min(gunDates[gunTypeIndex].MaxAmmoClip - ammoClip[gunTypeIndex], ammunition[gunTypeIndex]);

            // ’e–ò‚ª‚ ‚éê‡‚Ì‚İƒŠƒ[ƒh
            if (ammoToReload > 0)
            {
                //@TODO: ŠÔ‚ª‚ ‚éÛ‚É‚±‚±‚ğ’²®‚·‚é
                // ƒAƒjƒ[ƒVƒ‡ƒ“
                // gunAnimator.SetTrigger("Reload");

                // Š’e–ò‚ğXV‚Æ’e–ò‘•“U
                ammunition[gunTypeIndex] -= ammoToReload;
                ammoClip[gunTypeIndex] += ammoToReload;
            }
        }
    }
}